
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://localhost:3306/diet?useUnicode=true&serverTimezone=UTC&allowPublicKeyRetrieval=TRUE
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
  error:
    whitelabel:
      enabled: true
      include-stacktrace: true
      include-message: true
logging:
  level:
    root: info
